### ISSUE TITLE
Rest distance settings for DistanceJoint in Maze example

### ISSUE THREAD

**Issue by NordelDev** [dyn4j/dyn4j-samples#1]
Hi William,

first of all, congratulations on the new library version. I really really like it.

Also the new `SimulationFrame` and its new feature are quite amazing.

---

I have one question to the sample `Maze` ([link](https://github.com/dyn4j/dyn4j-samples/blob/master/src/main/java/org/dyn4j/samples/Maze.java))

Can you explain to me why you use the following code

```
protected void handleEvents() {
...
[192] dj.setDistance(b1.getWorldCenter().distance(b2.getWorldCenter()));
[193] dj.setDistance(0);
....
```

What is the purpose to set the rest distance of the `DistanceJoint` at first to the distance based on the center of the two linked `SimulationBody` and then right after that to set the rest distance to 0? Is there something I missed in the new library version with regard to that joint?

---

For the samples there isn't a "discussion" tab so I hope it is okay that I posted my question here.

Best regards,

Carsten

**Comment by wnbittle** [comment]
Thanks, on both accounts!  Did you mean the [Organize](https://github.com/dyn4j/dyn4j-samples/tree/master/src/main/java/org/dyn4j/samples/Organize.java) sample?

It's a mistake - you don't need the first setDistance call.  I think this was some code left over from some testing of mine.  By default, the DistanceJoint will set the target distance to the initial distance between the anchor points at time of creation.  For this sample, we need to override it so that the joints pull the bodies together.

**Comment by NordelDev** [comment]
Oh yes you are totally right. I meant indeed `Organize`. Sorry about that.

Thank you for the clarification about the setting of the rest distance :-)
