### ISSUE TITLE
Cannot Build Samples Repo

### ISSUE THREAD

**Issue by semihartan** [dyn4j/dyn4j-samples#3]
Hello William,

I am interested in physics engines and I just wanted to give a try your dyn4j. I am not a Java programmer and don't have any experience of Java and Eclipse IDE Environment, therefore I am facing with some error when I try to "Run As" your sample classes. It gives me an error message like that:

> Error: Could not find or load main class org.dyn4j.samples.UsingGraphics2D
> Caused by: java.lang.ClassNotFoundException: org.dyn4j.samples.UsingGraphics2D  

for each class in src folder. What should I do? I followed up with [that](https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean?page=1&tab=votes#tab-top) SO question but couldn't succeed to determine what causes the error exactly. Could you help me please?

**Comment by wnbittle** [comment]
@semihartan If you are using the Eclipse IDE then you should be able to just Run As as shown in the [getting started video](https://www.youtube.com/watch?v=OqOcT8z-m_w).

The SO response seemed focused on the Java command line which Eclipse hides.  When you use Run As in Eclipse it will perform the necessary command line operations to build and run the application.  When using the command line manually, the process for building a Java application is to compile first with `javac` and then to run with `java`.  `javac` produces `.class` files which are the byte-code files that the Java VM runs.  The `java` command starts the Java VM and runs a `.class` file that has a `public static void main(String[] args)` method.  The `-classpath` argument to the `java` command is used to ensure all `.class` files that represent the application are loaded.

All that said, this is a very generic error that could mean a few things - the project can't be built (`javac` is failing), the `java` command cannot find the `.class` file because it's not on the classpath, or the classpath is set wrong, etc.  Are you getting this when running in Eclipse or are you trying to run from the command line?

Another factor involved here is that the Samples project uses Maven which is a dependency management like tool (think npm or nuget in the JavaScript and C# realms).  Following the video, you shouldn't have to worry about any of this though.  Any chance you can provide a screenshot or a more detailed description of the steps you are taking when you try to run the project?

**Comment by semihartan** [comment]
Hello again,

Before creating an issue here, I have watched your getting started video and have installed Eclipse to run your samples. Before installing Eclipse, I have downloaded and installed Java Runtime from [this](https://www.java.com/en/download/manual.jsp) website.

Before I clonned the repo, I created an HelloWorld console app to get a grasp of the java and eclipse environment. After that, I cloned the repo as you show in the video.  When I right click and Run As the individual sample classes, I get the specified error.

![image](https://user-images.githubusercontent.com/13886510/153631424-f2d61e86-b02d-4e43-a1cd-9ba6cc13638b.png)

I notice the cross sign in the project icon. 

I am not sure but maybe, creating a HelloWorld console app previously, can cause the error. Except that I didn't anything suspicous. 

> The SO response seemed focused on the Java command line which Eclipse hides. When you use Run As in Eclipse it will 
perform the necessary command line operations to build and run the application. When using the command line manually, the process for building a Java application is to compile first with javac and then to run with java. javac produces .class files which are the byte-code files that the Java VM runs. The java command starts the Java VM and runs a .class file that has a public static void main(String[] args) method. The -classpath argument to the java command is used to ensure all .class files that represent the application are loaded.

Then, the java files cannot be compiled because I can't see any compiled java classes in target folder.

![image](https://user-images.githubusercontent.com/13886510/153632888-3ce629b7-a969-4a7c-ab3d-6f42f47ab96b.png)

Build menu item is not enabled. I can't build the project.
![image](https://user-images.githubusercontent.com/13886510/153633294-53ba818a-d914-4868-9577-5c342ac5f289.png)

I think that window shows the compilation errors.

![image](https://user-images.githubusercontent.com/13886510/153634376-aac823d8-e765-4818-b70f-9705e544598e.png)

If you need any further details, ask me. I really want to solve that.

**Comment by wnbittle** [comment]
Thank you for the additional details.  You are correct, it's not building.  From what I can tell it's not building because there isn't a compatible Java 6 runtime/JDK installed.  You don't need Java 6, you can use any Java version greater than or equal to Java 6.  Try swapping out the JRE with your workspace default or whichever version you downloaded.

![image](https://user-images.githubusercontent.com/11467997/153698833-59bf8070-e708-4c6d-bc00-d11d53738f81.png)
![image](https://user-images.githubusercontent.com/11467997/153698886-bf3c3f64-5f01-42a5-9791-634dade8bf62.png)

**Comment by semihartan** [comment]
Thank you for response and help. I managed to made it build!

**Comment by wnbittle** [comment]
Awesome, glad to hear!
